// Simple utility to convert a file into a Go byte array

// Clint Caywood

// http://github.com/cratonica/2goarray
package main

import (
	"bufio"
	"fmt"
	"github.com/codegangsta/cli"
	"io"
	"io/ioutil"
	"os"
)

const (
	NAME    = "2goarray"
	VERSION = "0.3.0"
	URL     = "http://github.com/cratonica/2goarray"
)

func main() {
	// the commandline interface
	app := cli.NewApp()
	app.Name = NAME
	app.Version = VERSION
	app.Author = NAME + " contributors"
	app.Email = URL + "/graphs/contributors"
	app.Usage = "A simple utility to encode a file into a Go byte array"
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "input, i",
			Value: "",
			Usage: "path to the input json file",
		},
		cli.StringFlag{
			Name:  "output, o",
			Value: "",
			Usage: "filepath to write to the generated source",
		},
		cli.StringFlag{
			Name:  "package-name, p",
			Value: "",
			Usage: "name of the package",
		},
		cli.StringFlag{
			Name:  "array-name, a",
			Value: "",
			Usage: "name of the byte array",
		},
		cli.BoolFlag{
			Name:  "no-generated-info, ni",
			Usage: "no 'generated by' info at the first code line",
		},
		cli.BoolFlag{
			Name:  "no-package, np",
			Usage: "no 'package' code",
		},
	}
	app.Action = cliAction
	app.Run(os.Args)
}

func cliAction(c *cli.Context) {
	// create generator object.
	// here we store the generator parameter
	code := NewGenerator()

	// get the cli flag values
	input := c.String("input")
	output := c.String("output")
	code.PackageName = c.String("package-name")
	code.VarName = c.String("array-name")
	code.GenerateInfo = !c.Bool("no-generated-info")
	code.GeneratePackage = !c.Bool("no-package")

	// check if the input flag was set
	if input != "" {
		// read the input file
		code.SetDataFromFile(input)
	} else {
		// read the input from stdin
		if isTerminal() {
			fmt.Println("\nPlease pipe the file you wish to encode into stdin or use the -input flag\n")
			os.Exit(1)
		}
		reader := bufio.NewReader(os.Stdin)
		text, err := reader.ReadString('\n')
		if err != nil && err != io.EOF {
			fmt.Errorf("Error: %v", err)
			os.Exit(1)
		}
		code.SetData([]byte(text))
	}

	if code.VarName == "" {
		code.VarName = "DATA"
	}

	// generate the code
	genCode := code.GenerateCode()

	// write or print generated code
	if output != "" {
		fmt.Println("OK, write to file", output)
		ioutil.WriteFile(output, genCode, 0755)
		os.Exit(0)
	}
	fmt.Print(string(genCode))
}
